2:4.7.0+dfsg-1 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/ctdb/config/functions b/ctdb/config/functions
--- a/ctdb/config/functions
+++ b/ctdb/config/functions
@@ -97,26 +97,6 @@ loadconfig () {
 
 ##############################################################
 
-# CTDB_SCRIPT_DEBUGLEVEL can be overwritten by setting it in a
-# configuration file.
-debug ()
-{
-    if [ "${CTDB_SCRIPT_DEBUGLEVEL:-NOTICE}" = "DEBUG" ] ; then
-	# If there are arguments then echo them.  Otherwise expect to
-	# use stdin, which allows us to pass lots of debug using a
-	# here document.
-	if [ -n "$1" ] ; then
-	    echo "DEBUG: $*"
-	else
-	    sed -e 's@^@DEBUG: @'
-	fi
-    else
-	if [ -z "$1" ] ; then
-	    cat >/dev/null
-	fi
-    fi
-}
-
 die ()
 {
     _msg="$1"
@@ -358,67 +338,40 @@ ctdb_check_directories()
 # usage: ctdb_check_tcp_ports <ports...>
 ######################################################
 
-# This flag file is created when a service is initially started.  It
-# is deleted the first time TCP port checks for that service succeed.
-# Until then ctdb_check_tcp_ports() prints a more subtle "error"
-# message if a port check fails.
-_ctdb_check_tcp_common ()
-{
-    assert_service_name
-    _d="${CTDB_SCRIPT_VARDIR}/failcount"
-    _ctdb_service_started_file="${_d}/${service_name}.started"
-}
-
-ctdb_check_tcp_init ()
-{
-    _ctdb_check_tcp_common
-    mkdir -p "${_ctdb_service_started_file%/*}" # dirname
-    touch "$_ctdb_service_started_file"
-}
-
 # Check whether something is listening on all of the given TCP ports
 # using the "ctdb checktcpport" command.
 ctdb_check_tcp_ports()
 {
-    if [ -z "$1" ] ; then
-	echo "INTERNAL ERROR: ctdb_check_tcp_ports - no ports specified"
-	exit 1
-    fi
+	if [ -z "$1" ] ; then
+		echo "INTERNAL ERROR: ctdb_check_tcp_ports - no ports specified"
+		exit 1
+	fi
 
-    for _p ; do  # process each function argument (port)
-	_cmd="$CTDB checktcpport $_p"
-	_out=$($_cmd 2>&1)
-	_ret=$?
-	case "$_ret" in
-	    0)
-		_ctdb_check_tcp_common
-		if [ ! -f "$_ctdb_service_started_file" ] ; then
-		    echo "ERROR: $service_name tcp port $_p is not responding"
-		    debug "\"ctdb checktcpport $_p\" was able to bind to port"
-		else
-		    echo "INFO: $service_name tcp port $_p is not responding"
-		fi
+	for _p ; do  # process each function argument (port)
+		_cmd="$CTDB checktcpport $_p"
+		_out=$($_cmd 2>&1)
+		_ret=$?
+		case "$_ret" in
+		0)
+			echo "$service_name not listening on TCP port $_p"
+			return 1
+			;;
+		98)
+			# Couldn't bind, something already listening, next port
+			continue
+			;;
+		*)
+			echo "unexpected error (${_ret}) running \"${_cmd}\""
+			if [ -n "$_out" ] ; then
+				echo "$_out"
+			fi
+			return $_ret
+			;;
+		esac
+	done
 
-		return 1
-		;;
-	    98)
-		# Couldn't bind, something already listening, next port...
-		continue
-		;;
-	    *)
-		echo "ERROR: unexpected error running \"ctdb checktcpport\""
-		debug <<EOF
-$CTDB checktcpport (exited with $_ret) with output:
-$_out"
-EOF
-		return $_ret
-	esac
-    done
-
-    # All ports listening
-    _ctdb_check_tcp_common
-    rm -f "$_ctdb_service_started_file"
-    return 0
+	# All ports listening
+	return 0
 }
 
 ######################################################
@@ -433,19 +386,6 @@ ctdb_check_unix_socket() {
         echo "ERROR: $service_name socket $socket_path not found"
         return 1
     fi
-}
-
-######################################################
-# check a command returns zero status
-# usage: ctdb_check_command <command>
-######################################################
-ctdb_check_command ()
-{
-    _out=$("$@" 2>&1) || {
-	echo "ERROR: $* returned error"
-	echo "$_out" | debug
-	exit 1
-    }
 }
 
 ################################################
@@ -474,7 +414,6 @@ kill_tcp_connections ()
 		139|445) __oneway=true ;;
 	    esac
 
-	    echo "Killing TCP connection $_src $_dst"
 	    _connections="${_connections}${_nl}${_src} ${_dst}"
 	    if ! $__oneway ; then
 		_connections="${_connections}${_nl}${_dst} ${_src}"
@@ -493,15 +432,22 @@ kill_tcp_connections ()
 		return
 	}
 
-	_remaining=$(get_tcp_connections_for_ip "$_ip" | wc -l)
-
-	if [ "$_remaining" -eq 0 ] ; then
-		echo "Killed $_killcount TCP connections to released IP $_ip"
-		return
+	_connections=$(get_tcp_connections_for_ip "$_ip")
+	if [ -z "$_connections" ] ; then
+		_remaining=0
+	else
+		_remaining=$(echo "$_connections" | wc -l)
 	fi
 
-	_t="${_remaining}/${_killcount}"
-	echo "Failed to kill TCP connections for IP $_ip (${_t} remaining)"
+	_actually_killed=$((_killcount - _remaining))
+
+	_t="${_actually_killed}/${_killcount}"
+	echo "Killed ${_t} TCP connections to released IP $_ip"
+
+	if [ -n "$_connections" ] ; then
+		echo "Remaining connections:"
+		echo "$_connections" | sed -e 's|^|  |'
+	fi
     }
 }
 
@@ -782,33 +728,6 @@ ctdb_setup_service_state_dir ()
 	echo "$_service_state_dir"
 }
 
-########################################################
-# Managed status history, for auto-start/stop
-
-_ctdb_managed_common ()
-{
-    _ctdb_managed_file="${CTDB_SCRIPT_VARDIR}/managed_history/${service_name}"
-}
-
-ctdb_service_managed ()
-{
-    _ctdb_managed_common
-    mkdir -p "${_ctdb_managed_file%/*}" # dirname
-    touch "$_ctdb_managed_file"
-}
-
-ctdb_service_unmanaged ()
-{
-    _ctdb_managed_common
-    rm -f "$_ctdb_managed_file"
-}
-
-is_ctdb_previously_managed_service ()
-{
-    _ctdb_managed_common
-    [ -f "$_ctdb_managed_file" ]
-}
-
 ##################################################################
 # Reconfigure a service on demand
 
@@ -854,7 +773,7 @@ service_reconfigure ()
 }
 
 ##################################################################
-# Does CTDB manage this service? - and associated auto-start/stop
+# Does CTDB manage this service?
 
 ctdb_compat_managed_service ()
 {
@@ -891,75 +810,6 @@ is_ctdb_managed_service ()
 
     # Return 0 if "<space>$service_name<space>" appears in $t
     [ "${t#* ${service_name} }" != "${t}" ]
-}
-
-ctdb_start_stop_service ()
-{
-    assert_service_name
-
-    # Allow service-start/service-stop pseudo-events to start/stop
-    # services when we're not auto-starting/stopping and we're not
-    # monitoring.
-    case "$event_name" in
-	service-start)
-	    if is_ctdb_managed_service ; then
-		die 'service-start event not permitted when service is managed'
-	    fi
-	    if [ "$CTDB_SERVICE_AUTOSTARTSTOP" = "yes" ] ; then
-		die 'service-start event not permitted with CTDB_SERVICE_AUTOSTARTSTOP=yes'
-	    fi
-	    ctdb_service_start
-	    exit $?
-	    ;;
-	service-stop)
-	    if is_ctdb_managed_service ; then
-		die 'service-stop event not permitted when service is managed'
-	    fi
-	    if [ "$CTDB_SERVICE_AUTOSTARTSTOP" = "yes" ] ; then
-		die 'service-stop event not permitted with CTDB_SERVICE_AUTOSTARTSTOP=yes'
-	    fi
-	    ctdb_service_stop
-	    exit $?
-	    ;;
-    esac
-
-    # Do nothing unless configured to...
-    [ "$CTDB_SERVICE_AUTOSTARTSTOP" = "yes" ] || return 0
-
-    [ "$event_name" = "monitor" ] || return 0
-
-    if is_ctdb_managed_service ; then
-	if ! is_ctdb_previously_managed_service ; then
-	    echo "Starting service \"$service_name\" - now managed"
-	    background_with_logging ctdb_service_start
-	    exit $?
-	fi
-    else
-	if is_ctdb_previously_managed_service ; then
-	    echo "Stopping service \"$service_name\" - no longer managed"
-	    background_with_logging ctdb_service_stop
-	    exit $?
-	fi
-    fi
-}
-
-ctdb_service_start ()
-{
-    # The service is marked managed if we've ever tried to start it.
-    ctdb_service_managed
-
-    service_start || return $?
-
-    # Intentionally have this use $service_name as default
-    # shellcheck disable=SC2119
-    ctdb_counter_init
-    ctdb_check_tcp_init
-}
-
-ctdb_service_stop ()
-{
-    ctdb_service_unmanaged
-    service_stop
 }
 
 # Default service_start() and service_stop() functions.
@@ -1168,4 +1018,3 @@ update_tickles ()
 }
 
 script_name="${0##*/}"       # basename
-event_name="$1"
