2:4.9.0+dfsg-1 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/ctdb/config/functions b/ctdb/config/functions
--- a/ctdb/config/functions
+++ b/ctdb/config/functions
@@ -11,14 +11,13 @@ export CTDB_BASE
 # CTDB_VARDIR is used elsewhere
 # shellcheck disable=SC2034
 CTDB_VARDIR="/usr/local/var/lib/ctdb"
-ctdb_rundir="/usr/local/var/run/ctdb"
 
 CTDB="${CTDB:-/usr/local/bin/ctdb}"
 
 # Only (and always) override these variables in test code
 
 if [ -z "$CTDB_SCRIPT_VARDIR" ] ; then
-    CTDB_SCRIPT_VARDIR="/usr/local/var/lib/ctdb/state"
+    CTDB_SCRIPT_VARDIR="/usr/local/var/lib/ctdb/scripts"
 fi
 
 if [ -z "$CTDB_SYS_ETCDIR" ] ; then
@@ -32,67 +31,48 @@ fi
 #######################################
 # pull in a system config file, if any
 
-rewrite_ctdb_options ()
+load_system_config ()
 {
-    case "$CTDB_DBDIR" in
-	tmpfs|tmpfs:*)
-	    _opts_defaults="mode=700"
-	    # Get any extra options specified after colon
-	    if [ "$CTDB_DBDIR" = "tmpfs" ] ; then
-		_opts=""
-	    else
-		_opts="${CTDB_DBDIR#tmpfs:}"
-	    fi
-	    # It is OK to repeat mount options - last value wins.
-	    # CTDB_DBDIR_TMPFS_OPTIONS is used by ctdbd_wrapper
-	    # shellcheck disable=SC2034
-	    CTDB_DBDIR_TMPFS_OPTIONS="${_opts_defaults}${_opts:+,}${_opts}"
+	if [ -z "$1" ] ; then
+		return
+	fi
 
-	    CTDB_DBDIR="${ctdb_rundir}/CTDB_DBDIR"
-	    ;;
-	*)
-	    # shellcheck disable=SC2034
-	    CTDB_DBDIR_TMPFS_OPTIONS=""
-    esac
+	if [ -f "${CTDB_SYS_ETCDIR}/sysconfig/$1" ]; then
+		. "${CTDB_SYS_ETCDIR}/sysconfig/$1"
+	elif [ -f "${CTDB_SYS_ETCDIR}/default/$1" ]; then
+		. "${CTDB_SYS_ETCDIR}/default/$1"
+	fi
 }
 
-_loadconfig() {
-
-    if [ -z "$1" ] ; then
-	foo="${service_config:-${service_name}}"
-	if [ -n "$foo" ] ; then
-	    loadconfig "$foo"
-	    return
+# load_script_options [ component script ]
+#   script is an event script name relative to a component
+#   component is currently ignored
+load_script_options ()
+{
+	if [ $# -eq 2 ] ; then
+		_script="$2"
+	elif [ $# -eq 0  ] ; then
+		_script=""
+	else
+		die "usage: load_script_options [ component script ]"
 	fi
-    fi
 
-    if [ "$1" != "ctdb" ] ; then
-	loadconfig "ctdb"
-    fi
+	_options="${CTDB_BASE}/script.options"
 
-    if [ -z "$1" ] ; then
-	return
-    fi
-
-    if [ -f "${CTDB_SYS_ETCDIR}/sysconfig/$1" ]; then
-	. "${CTDB_SYS_ETCDIR}/sysconfig/$1"
-    elif [ -f "${CTDB_SYS_ETCDIR}/default/$1" ]; then
-	. "${CTDB_SYS_ETCDIR}/default/$1"
-    elif [ -f "${CTDB_BASE}/sysconfig/$1" ]; then
-	. "${CTDB_BASE}/sysconfig/$1"
-    fi
-
-    if [ "$1" = "ctdb" ] ; then
-	_config="${CTDBD_CONF:-${CTDB_BASE}/ctdbd.conf}"
-	if [ -r "$_config" ] ; then
-	    . "$_config"
+	if [ -r "$_options" ] ; then
+		. "$_options"
 	fi
-	rewrite_ctdb_options
-    fi
-}
 
-loadconfig () {
-    _loadconfig "$@"
+	if [ -n "$_script" ] ; then
+		_s="${CTDB_BASE}/events/legacy/${_script}"
+	else
+		_s="${0%.script}"
+	fi
+	_options="${_s}.options"
+
+	if [ -r "$_options" ] ; then
+		. "$_options"
+	fi
 }
 
 ##############################################################
@@ -171,16 +151,18 @@ ctdb_check_args ()
 # determine on what type of system (init style) we are running
 detect_init_style()
 {
-    # only do detection if not already set:
-    [ -z "$CTDB_INIT_STYLE" ] || return
+	# only do detection if not already set:
+	if [ -n "$CTDB_INIT_STYLE" ] ; then
+		return
+	fi
 
-    if [ -x /sbin/startproc ]; then
-        CTDB_INIT_STYLE="suse"
-    elif [ -x /sbin/start-stop-daemon ]; then
-        CTDB_INIT_STYLE="debian"
-    else
-        CTDB_INIT_STYLE="redhat"
-    fi
+	if [ -x /sbin/startproc ]; then
+		CTDB_INIT_STYLE="suse"
+	elif [ -x /sbin/start-stop-daemon ]; then
+		CTDB_INIT_STYLE="debian"
+	else
+		CTDB_INIT_STYLE="redhat"
+	fi
 }
 
 ######################################################
@@ -250,6 +232,43 @@ ctdb_get_ip_address ()
     cat "$_ip_addr_file"
 }
 
+# Cached retrieval of database options for use by event scripts.
+#
+# If the variables are already set then they should not be overwritten
+# - this should only happen during event script testing.
+ctdb_get_db_options ()
+{
+	_db_opts_file="${CTDB_SCRIPT_VARDIR}/db_options.cache"
+
+	if [ ! -f "$_db_opts_file" ] ; then
+		{
+			ctdb_translate_option "database" \
+					      "volatile database directory" \
+					      "CTDB_DBDIR"
+			ctdb_translate_option "database" \
+					      "persistent database directory" \
+					      "CTDB_DBDIR_PERSISTENT"
+			ctdb_translate_option "database" \
+					      "state database directory" \
+					      "CTDB_DBDIR_STATE"
+		} >"$_db_opts_file"
+	fi
+
+	. "$_db_opts_file"
+}
+
+ctdb_translate_option ()
+{
+	_section="$1"
+	_opt="$2"
+	_variable="$3"
+
+	# ctdb-config already prints an error if something goes wrong
+	_t=$("${CTDB_HELPER_BINDIR}/ctdb-config" get "$_section" "$_opt") || \
+		exit $?
+	echo "${_variable}=\"${_t}\""
+}
+
 ######################################################
 # wrapper around /proc/ settings to allow them to be hooked
 # for testing
@@ -300,7 +319,9 @@ program_stack_traces ()
 # Ensure $service_name is set
 assert_service_name ()
 {
-    [ -n "$service_name" ] || die "INTERNAL ERROR: \$service_name not set"
+	# service_name is set by the event script
+	# shellcheck disable=SC2154
+	[ -n "$service_name" ] || die "INTERNAL ERROR: \$service_name not set"
 }
 
 ######################################################
@@ -592,7 +613,7 @@ drop_all_public_ips ()
 	# shellcheck disable=SC2034
 	while read _ip _x ; do
 		drop_ip "$_ip"
-	done <"${CTDB_PUBLIC_ADDRESSES:-/dev/null}"
+	done <"${CTDB_BASE}/public_addresses"
 }
 
 flush_route_cache ()
@@ -697,10 +718,21 @@ interface_monitor ()
 
 ########################################################
 # Simple counters
-_ctdb_counter_common () {
-    _service_name="${1:-${service_name:-${script_name}}}"
-    _counter_file="${CTDB_SCRIPT_VARDIR}/failcount/${_service_name}"
-    mkdir -p "${_counter_file%/*}" # dirname
+_ctdb_counter_common ()
+{
+	[ $# -le 1 ] || die "usage: _ctdb_counter_common [name]"
+
+	if [ $# -eq 1 ] ; then
+		_counter_name="${1}.failcount"
+	else
+		_counter_name="failcount"
+	fi
+
+	if [ -z "$script_state_dir" ] ; then
+		die "ctdb_counter_* functions need ctdb_setup_state_dir()"
+	fi
+
+	_counter_file="${script_state_dir}/${_counter_name}"
 }
 # Some code passes an argument
 # shellcheck disable=SC2120
@@ -718,20 +750,27 @@ ctdb_counter_incr () {
 ctdb_counter_get () {
     _ctdb_counter_common "$1"
     # unary counting!
-    stat -c "%s" "$_counter_file" 2>/dev/null || echo 0
+    _val=$(wc -c < "$_counter_file" 2>/dev/null || echo 0)
+    # Strip leading spaces from ouput of wc (on freebsd)
+    # shellcheck disable=SC2086
+    echo $_val
 }
 
 ########################################################
 
-ctdb_setup_service_state_dir ()
+# ctdb_setup_state_dir <type> <name>
+#   Sets/creates script_state_dir)
+ctdb_setup_state_dir ()
 {
-	_s="${1:-${service_name}}"
+	[ $# -eq 2 ] || die "usage: ctdb_setup_state_dir <type> <name>"
 
-	_service_state_dir="${CTDB_SCRIPT_VARDIR}/service_state/${_s}"
-	mkdir -p "$_service_state_dir" ||
-		die "Error creating state dir \"${_service_state_dir}\""
+	_type="$1"
+	_name="$2"
 
-	echo "$_service_state_dir"
+	script_state_dir="${CTDB_SCRIPT_VARDIR}/${_type}/${_name}"
+
+	mkdir -p "$script_state_dir" || \
+		die "Error creating script state dir \"${script_state_dir}\""
 }
 
 ##################################################################
@@ -739,9 +778,11 @@ ctdb_setup_service_state_dir ()
 
 _ctdb_service_reconfigure_common ()
 {
-    _d="${CTDB_SCRIPT_VARDIR}/service_status/${service_name}"
-    mkdir -p "$_d"
-    _ctdb_service_reconfigure_flag="$_d/reconfigure"
+	if [ -z "$script_state_dir" ] ; then
+		die "ctdb_service_*_reconfigure() needs ctdb_setup_state_dir()"
+	fi
+
+	_ctdb_service_reconfigure_flag="${script_state_dir}/need_reconfigure"
 }
 
 ctdb_service_needs_reconfigure ()
@@ -778,48 +819,8 @@ service_reconfigure ()
     :
 }
 
-##################################################################
-# Does CTDB manage this service?
-
-ctdb_compat_managed_service ()
-{
-    if [ "$1" = "yes" -a "$2" = "$service_name" ] ; then
-	CTDB_MANAGED_SERVICES="$CTDB_MANAGED_SERVICES $2"
-    fi
-}
-
-is_ctdb_managed_service ()
-{
-    assert_service_name
-
-    # $t is used just for readability and to allow better accurate
-    # matching via leading/trailing spaces
-    t=" $CTDB_MANAGED_SERVICES "
-
-    # Return 0 if "<space>$service_name<space>" appears in $t
-    if [ "${t#* ${service_name} }" != "${t}" ] ; then
-	return 0
-    fi
-
-    # If above didn't match then update $CTDB_MANAGED_SERVICES for
-    # backward compatibility and try again.
-    ctdb_compat_managed_service "$CTDB_MANAGES_VSFTPD"   "vsftpd"
-    ctdb_compat_managed_service "$CTDB_MANAGES_SAMBA"    "samba"
-    ctdb_compat_managed_service "$CTDB_MANAGES_WINBIND"  "winbind"
-    ctdb_compat_managed_service "$CTDB_MANAGES_HTTPD"    "apache2"
-    ctdb_compat_managed_service "$CTDB_MANAGES_HTTPD"    "httpd"
-    ctdb_compat_managed_service "$CTDB_MANAGES_ISCSI"    "iscsi"
-    ctdb_compat_managed_service "$CTDB_MANAGES_CLAMD"    "clamd"
-    ctdb_compat_managed_service "$CTDB_MANAGES_NFS"      "nfs"
-
-    t=" $CTDB_MANAGED_SERVICES "
-
-    # Return 0 if "<space>$service_name<space>" appears in $t
-    [ "${t#* ${service_name} }" != "${t}" ]
-}
-
 # Default service_start() and service_stop() functions.
- 
+
 # These may be overridden in an eventscript.
 service_start ()
 {
@@ -866,8 +867,8 @@ if ! type mktemp >/dev/null 2>&1 ; then
 	fi
 	_d="${TMPDIR:-/tmp}"
 	_hex10=$(dd if=/dev/urandom count=20 2>/dev/null | \
-	    md5sum | \
-	    sed -e 's@\(..........\).*@\1@')
+	    cksum | \
+	    awk '{print $1}')
 	_t="${_d}/tmp.${_hex10}"
 	(
 	    umask 077
@@ -1008,10 +1009,6 @@ update_tickles ()
 ########################################################
 # load a site local config file
 ########################################################
-
-[ -n "$CTDB_RC_LOCAL" -a -x "$CTDB_RC_LOCAL" ] && {
-	. "$CTDB_RC_LOCAL"
-}
 
 [ -x "${CTDB_BASE}/rc.local" ] && {
 	. "${CTDB_BASE}/rc.local"
diff --git a/ctdb/config/statd-callout b/ctdb/config/statd-callout
--- a/ctdb/config/statd-callout
+++ b/ctdb/config/statd-callout
@@ -20,22 +20,73 @@ die ()
     exit 1
 }
 
-loadconfig ctdb
-loadconfig nfs
+load_system_config "nfs"
 
 [ -n "$NFS_HOSTNAME" ] || \
     die "NFS_HOSTNAME is not configured. statd-callout failed"
 
-# A handy newline
-nl="
-"
+############################################################
 
-service_state_dir=$(ctdb_setup_service_state_dir "statd-callout") || exit $?
+ctdb_setup_state_dir "service" "nfs"
 
-cd "$service_state_dir" || \
-    die "Failed to change directory to \"${service_state_dir}\""
+# script_state_dir set by ctdb_setup_state_dir()
+# shellcheck disable=SC2154
+d="${script_state_dir}/statd-callout"
+
+mkdir -p "$d" || die "Failed to create directory \"${d}\""
+cd "$d" || die "Failed to change directory to \"${d}\""
 
 pnn=$(ctdb_get_pnn)
+
+############################################################
+
+send_notifies ()
+{
+	_smnotify="${CTDB_HELPER_BINDIR}/smnotify"
+
+	# State must monotonically increase, across the entire
+	# cluster.  Use seconds since epoch and hope the time is in
+	# sync across nodes.  Even numbers mean service is shut down,
+	# odd numbers mean service is started.
+
+	# Intentionally round to an even number
+	# shellcheck disable=SC2017
+	_state_even=$(( $(date '+%s') / 2 * 2))
+
+	_prev=""
+	while read _sip _cip ; do
+		# NOTE: Consider optimising smnotify to read all the
+		# data from stdin and then run it in the background.
+
+		# Reset stateval for each serverip
+		if [ "$_sip" != "$_prev" ] ; then
+			_stateval="$_state_even"
+		fi
+
+		# Send notifies for server shutdown
+		"$_smnotify" --client="$_cip" --ip="$_sip" \
+			     --server="$_sip" --stateval="$_stateval"
+		"$_smnotify" --client="$_cip" --ip="$_sip" \
+			     --server="$NFS_HOSTNAME" --stateval="$_stateval"
+
+		# Send notifies for server startup
+		_stateval=$((_stateval + 1))
+		"$_smnotify" --client="$_cip" --ip="$_sip" \
+			     --server="$_sip" --stateval="$_stateval"
+		"$_smnotify" --client="$_cip" --ip="$_sip" \
+			     --server="$NFS_HOSTNAME" --stateval="$_stateval"
+	done
+}
+
+delete_records ()
+{
+	while read _sip _cip ; do
+		_key="statd-state@${_sip}@${_cip}"
+		echo "\"${_key}\" \"\""
+	done | $CTDB ptrans "ctdb.tdb"
+}
+
+############################################################
 
 case "$1" in
     # Keep a single file to keep track of the last "add-client" or
@@ -91,10 +142,14 @@ case "$1" in
                 printf "/statd-state@%s@/p\n", ip }')
 	# Intentional multi-word expansion for multiple files
 	# shellcheck disable=SC2086
-        if sed -n "$sed_expr" $files | $CTDB ptrans "ctdb.tdb" ; then
-            rm $files
+	items=$(sed -n "$sed_expr" $files)
+	if [ -n "$items" ] ; then
+		if echo "$items"  | $CTDB ptrans "ctdb.tdb" ; then
+			# shellcheck disable=SC2086
+			rm $files
+		fi
 	fi
-        ;;
+	;;
 
     notify)
 	# we must restart the lockmanager (on all nodes) so that we get
@@ -112,16 +167,6 @@ case "$1" in
 	# ping any clients
 	rm -f /var/lib/nfs/statd/sm/*
 	rm -f /var/lib/nfs/statd/sm.bak/*
-
-	# we must keep a monotonically increasing state variable for the entire
-	# cluster  so state always increases when ip addresses fail from one
-	# node to another
-	# We use epoch and hope the nodes are close enough in clock.
-	# Even numbers mean service is shut down, odd numbers mean
-	# service is started.
-	# Intentionally round to an even number
-	# shellcheck disable=SC2017
-	state_even=$(( $(date '+%s') / 2 * 2))
 
 	# We must also let some time pass between stopping and
 	# restarting the lock manager.  Otherwise there is a window
@@ -175,39 +220,8 @@ case "$1" in
 	statd_state=$($CTDB catdb ctdb.tdb | sed -n "$sed_expr" | sort)
 	[ -n "$statd_state" ] || exit 0
 
-	smnotify="${CTDB_HELPER_BINDIR}/smnotify"
-	prev=""
-	echo "$statd_state" | {
-	    # This all needs to be in the same command group at the
-	    # end of the pipe so it doesn't get lost when the loop
-	    # completes.
-	    items=""
-	    while read sip cip ; do
-		# Collect item to delete from the DB
-		key="statd-state@${sip}@${cip}"
-		item="\"${key}\" \"\""
-		items="${items}${items:+${nl}}${item}"
-
-		# NOTE: Consider optimising smnotify to read all the
-		# data from stdin and then run it in the background.
-
-		# Reset stateval for each serverip
-		[ "$sip" = "$prev" ] || stateval="$state_even"
-		# Send notifies for server shutdown
-		"$smnotify" --client="$cip" --ip="$sip" \
-			    --server="$sip" --stateval="$stateval"
-		"$smnotify" --client="$cip" --ip="$sip" \
-			    --server="$NFS_HOSTNAME" --stateval="$stateval"
-		# Send notifies for server startup
-		stateval=$((stateval + 1))
-		"$smnotify" --client="$cip" --ip="$sip" \
-			    --server="$sip" --stateval="$stateval"
-		"$smnotify" --client="$cip" --ip="$sip" \
-			    --server="$NFS_HOSTNAME" --stateval="$stateval"
-	    done
-
-	    echo "$items" | $CTDB ptrans "ctdb.tdb"
-	}
+	echo "$statd_state" | send_notifies
+	echo "$statd_state" | delete_records
 
 	# Remove any stale touch files (i.e. for IPs not currently
 	# hosted on this node and created since the last "update").
diff --git a/ctdb/tests/eventscripts/stubs/ctdb b/ctdb/tests/eventscripts/stubs/ctdb
--- a/ctdb/tests/eventscripts/stubs/ctdb
+++ b/ctdb/tests/eventscripts/stubs/ctdb
@@ -27,29 +27,35 @@ not_implemented ()
     exit $not_implemented_exit_code
 }
 
-# Don't set $POSIXLY_CORRECT here.
-_temp=$(getopt -n "$prog" -o "Xvhn:" -l help -- "$@") || \
-    usage
-
-eval set -- "$_temp"
-
 verbose=false
 machine_readable=false
 nodespec=""
 
-args="$*"
+args=""
 
-while true ; do
-    case "$1" in
-	-X) machine_readable=true ; shift ;;
-	-v) verbose=true ; shift ;;
-	-n) nodespec="$2" ; shift 2 ;;
-	--) shift ; break ;;
-	-h|--help|*) usage ;; # * shouldn't happen, so this is reasonable.
-    esac
+# Options and command argument can appear in any order, so when
+# getopts thinks it is done, process any non-option arguments and go
+# around again.
+while [ $# -gt 0 ] ; do
+	while getopts "Xvhn:?" opt ; do
+		case "$opt" in
+		X) machine_readable=true ;;
+		v) verbose=true ;;
+		n) nodespec="$OPTARG" ;;
+		\?|*) usage ;;
+		esac
+	done
+	shift $((OPTIND - 1))
+
+	# Anything left over must be a non-option arg
+	if [ $# -gt 0 ] ; then
+		args="${args}${args:+ }${1}"
+		shift
+	fi
 done
 
-[ $# -ge 1 ] || usage
+[ -n "$args" ] || usage
+set -- $args
 
 setup_tickles ()
 {
@@ -139,7 +145,7 @@ FAKE_CTDB_NODES_DISABLED="$FAKE_CTDB_NODE_STATE/0x4"
 
 ######################################################################
 
-# NOTE: all nodes share $CTDB_PUBLIC_ADDRESSES
+# NOTE: all nodes share public addresses file
 
 FAKE_CTDB_IP_LAYOUT="$FAKE_CTDB_STATE/ip-layout"
 
@@ -150,7 +156,7 @@ ip_reallocate ()
     (
 	flock 0
 
-	_pa="${CTDB_PUBLIC_ADDRESSES:-${CTDB_BASE}/public_addresses}"
+	_pa="${CTDB_BASE}/public_addresses"
 
 	if [ ! -s "$FAKE_CTDB_IP_LAYOUT" ] ; then
 	    sed -n -e 's@^\([^#][^/]*\)/.*@\1 -1@p' \
@@ -201,7 +207,7 @@ ctdb_ip ()
 
     # Join public addresses file with $FAKE_CTDB_IP_LAYOUT, and
     # process output line by line...
-    _pa="${CTDB_PUBLIC_ADDRESSES:-${CTDB_BASE}/public_addresses}"
+    _pa="${CTDB_BASE}/public_addresses"
     sed -e 's@/@ @' "$_pa" | sort | join - "$FAKE_CTDB_IP_LAYOUT" |
     while read _ip _bit _ifaces _pnn ; do
 	if $verbose ; then
@@ -241,9 +247,9 @@ ctdb_moveip ()
 
 	while read _i _pnn ; do
 	    if [ "$_ip" = "$_i" ] ; then
-		echo "$_ip $_target"
+		echo "$_i $_target"
 	    else
-		echo "$_ip $_pnn"
+		echo "$_i $_pnn"
 	    fi
 	done | sort >"$_t"
 	mv "$_t" "$FAKE_CTDB_IP_LAYOUT"
@@ -301,7 +307,6 @@ ctdb_nodestatus ()
 
 ctdb_setvar ()
 {
-    shift
     _var="$1"
 
     for _i in $FAKE_CTDB_TUNABLES_OK ; do
@@ -346,25 +351,25 @@ _t_del ()
 
 ctdb_pstore ()
 {
-    _t_setup "$2"
-    _t_put "$3" "$4"
+    _t_setup "$1"
+    _t_put "$2" "$3"
 }
 
 ctdb_pdelete ()
 {
-    _t_setup "$2"
-    _t_del "$3"
+    _t_setup "$1"
+    _t_del "$2"
 }
 
 ctdb_pfetch ()
 {
-    _t_setup "$2"
-    _t_get "$3" >"$4" 2>/dev/null
+    _t_setup "$1"
+    _t_get "$2" >"$3" 2>/dev/null
 }
 
 ctdb_ptrans ()
 {
-    _t_setup "$2"
+    _t_setup "$1"
 
     while IFS="" read _line ; do
 	_k=$(echo "$_line" | sed -n -e 's@^"\([^"]*\)" "[^"]*"$@\1@p')
@@ -380,7 +385,7 @@ ctdb_ptrans ()
 
 ctdb_catdb ()
 {
-    _t_setup "$2"
+    _t_setup "$1"
 
     # This will break on keys with spaces but we don't have any of
     # those yet.
@@ -406,89 +411,86 @@ EOF
 
 ######################################################################
 
-case "$1" in
-    gettickles) shift ; ctdb_gettickles "$@" ;;
-    addtickle) shift ; ctdb_addtickle "$@" ;;
-    deltickle) shift ; ctdb_deltickle "$@" ;;
-    pstore)  ctdb_pstore  "$@" ;;
-    pdelete) ctdb_pdelete "$@" ;;
-    pfetch)  ctdb_pfetch  "$@" ;;
-    ptrans)  ctdb_ptrans  "$@" ;;
-    catdb)   ctdb_catdb   "$@" ;;
-    ifaces)
+FAKE_CTDB_IFACES_DOWN="${FAKE_CTDB_STATE}/ifaces-down"
+rm -f "${FAKE_CTDB_IFACES_DOWN}"/*
+
+ctdb_ifaces()
+{
+	_f="${CTDB_BASE}/public_addresses"
+
+	if [ ! -f "$_f" ] ; then
+		die "Public addresses file \"${_f}\" not found"
+	fi
+
 	# Assume -Y.
 	echo "|Name|LinkStatus|References|"
-	_f="${CTDB_PUBLIC_ADDRESSES:-${CTDB_BASE}/public_addresses}"
-	if [ -r "$_f" ] ; then
-	    while read _ip _iface ; do
+	while read _ip _iface ; do
 		case "_$ip" in
-		    \#*) : ;;
-		    *)
+		\#*) : ;;
+		*)
 			_status=1
 			# For now assume _iface contains only 1.
 			if [ -f "{FAKE_CTDB_IFACES_DOWN}/${_iface}" ] ; then
-			    _status=0
+				_status=0
 			fi
 			# Nobody looks at references
 			echo "|${_iface}|${_status}|0|"
 		esac
-	    done <"$_f" |
-	    sort -u
-	fi
-	;;
-    setifacelink)
+	done <"$_f" |
+	sort -u
+}
+
+ctdb_setifacelink ()
+{
+	_iface="$1"
+	_state="$2"
+
+	mkdir -p "$FAKE_CTDB_IFACES_DOWN"
+
 	# Existence of file means CTDB thinks interface is down.
-	_f="${FAKE_CTDB_IFACES_DOWN}/$2"
-	case "$3" in
-	    up)   rm -f "$_f" ;;
-	    down) touch "$_f" ;;
-	    *)
-		echo "ctdb setifacelink: unsupported interface status $3"
-		exit 1
+	_f="${FAKE_CTDB_IFACES_DOWN}/${_iface}"
+
+	case "$_state" in
+	up)   rm -f "$_f" ;;
+	down) touch "$_f" ;;
+	*) die "ctdb setifacelink: unsupported interface status ${_state}" ;;
 	esac
-	;;
-    checktcpport)
+}
+
+######################################################################
+
+ctdb_checktcpport ()
+{
+	_port="$1"
+
 	for _i in $FAKE_TCP_LISTEN ; do
-	    if [ "$2" = "${_i##*:}" ] ; then
-		exit 98
-	    fi
+		if [ "$_port" = "$_i" ] ; then
+			exit 98
+		fi
 	done
 
 	exit 0
-	;;
-    scriptstatus)
-	$machine_readable || not_implemented "$1, without -X"
-	[ "$2" != "all" ] || not_implemented "scriptstatus all"
-	# For now just assume everything is good.
-	echo "|Type|Name|Code|Status|Start|End|Error Output...|"
-	for _i in "$CTDB_BASE/events.d/"*.* ; do
-	    _d1=$(date '+%s.%N')
-	    _b="${_i##*/}" # basename
+}
 
-	    _f="$FAKE_CTDB_SCRIPTSTATUS/$_b"
-	    if [ -r "$_f" ] ; then
-		read _code _status _err_out <"$_f"
-	    else
-		_code="0"
-		_status="OK"
-		if [ ! -x "$_i" ] ; then
-		    _status="DISABLED"
-		    _code="-8"
-		fi
-		_err_out=""
-	    fi
-	    _d2=$(date '+%s.%N')
-	    echo "|${2:-monitor}|${_b}|${_code}|${_status}|${_d1}|${_d2}|${_err_out}|"
-	done
-	;;
-    gratarp) : ;;  # Do nothing for now
-    ip)            ctdb_ip "$@" ;;
-    pnn|xpnn)      ctdb_pnn ;;
-    enable)        ctdb_enable "$@";;
-    disable)       ctdb_disable "$@";;
-    moveip)        ctdb_moveip "$@";;
-    shutdown)      ctdb_shutdown "$@";;
-    setvar)	   ctdb_setvar "$@" ;;
-    nodestatus)	   ctdb_nodestatus "$@" ;;
-    *) not_implemented "$1" ;;
-esac
+ctdb_gratarp ()
+{
+	# Do nothing for now
+	:
+}
+
+######################################################################
+
+cmd="$1"
+shift
+
+func="ctdb_${cmd}"
+
+# This could inadvertently run an external function instead of a local
+# function.  However, this can only happen if testing a script
+# containing a new ctdb command that is not implemented, so this is
+# unlikely to do harm.
+if type "$func" >/dev/null 2>&1 ; then
+	"$func" "$@"
+else
+	not_implemented "$cmd"
+fi
diff --git a/ctdb/tools/onnode b/ctdb/tools/onnode
--- a/ctdb/tools/onnode
+++ b/ctdb/tools/onnode
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 # Run commands on CTDB nodes.
 
@@ -31,7 +31,7 @@ usage ()
 Usage: onnode [OPTION] ... <NODES> <COMMAND> ...
   options:
     -c          Run in current working directory on specified nodes.
-    -f          Specify nodes file, overrides CTDB_NODES_FILE.
+    -f          Specify nodes file, overriding default.
     -i          Keep standard input open - the default is to close it.
     -n          Allow nodes to be specified by name.
     -o <prefix> Save standard output from each node to file <prefix>.<ip>
@@ -57,6 +57,7 @@ invalid_nodespec ()
 
 # Defaults.
 current=false
+ctdb_nodes_file=""
 parallel=false
 verbose=false
 quiet=false
@@ -69,44 +70,32 @@ if [ -z "$CTDB_BASE" ] ; then
     CTDB_BASE="/usr/local/etc/ctdb"
 fi
 
-. "${CTDB_BASE}/functions"
-loadconfig "ctdb"
-
 parse_options ()
 {
-    # $POSIXLY_CORRECT means that the command passed to onnode can
-    # take options and getopt won't reorder things to make them
-    # options ot onnode.
-    local temp
-    # Not on the previous line - local returns 0!
-    temp=$(POSIXLY_CORRECT=1 getopt -n "$prog" -o "cf:hno:pqvPi" -l help -- "$@")
+	local opt
 
-    # No! Checking the exit code afterwards is actually clearer...
-    # shellcheck disable=SC2181
-    [ $? -eq 0 ] || usage
+	while getopts "cf:hno:pqvPi?" opt ; do
+		case "$opt" in
+		c) current=true ;;
+		f) ctdb_nodes_file="$OPTARG" ;;
+		n) names_ok=true ;;
+		o) prefix="$OPTARG" ;;
+		p) parallel=true ;;
+		q) quiet=true ;;
+		v) verbose=true ;;
+		P) push=true ;;
+		i) stdin=true ;;
+		\?|h) usage ;;
+		esac
+	done
+	shift $((OPTIND - 1))
 
-    eval set -- "$temp"
+	if [ $# -lt 2 ] ; then
+		usage
+	fi
 
-    while true ; do
-	case "$1" in
-	    -c) current=true ; shift ;;
-	    -f) CTDB_NODES_FILE="$2" ; shift 2 ;;
-	    -n) names_ok=true ; shift ;;
-	    -o) prefix="$2" ; shift 2 ;;
-	    -p) parallel=true ; shift ;;
-	    -q) quiet=true ; shift ;;
-	    -v) verbose=true ; shift ;;
-	    -P) push=true ; shift ;;
-	    -i) stdin=true ; shift ;;
-	    --) shift ; break ;;
-	    -h|--help|*) usage ;; # Shouldn't happen, so this is reasonable.
-	esac
-    done
-
-    [ $# -lt 2 ] && usage
-
-    nodespec="$1" ; shift
-    command="$*"
+	nodespec="$1" ; shift
+	command="$*"
 }
 
 echo_nth ()
@@ -218,56 +207,50 @@ get_any_available_node ()
 
 get_nodes ()
 {
-    local all_nodes
+	local all_nodes
 
-    if [ -n "$CTDB_NODES_SOCKETS" ] ; then 
-	all_nodes="$CTDB_NODES_SOCKETS"
-    else
 	local f="${CTDB_BASE}/nodes"
-	if [ -n "$CTDB_NODES_FILE" ] ; then
-	    f="$CTDB_NODES_FILE"
-	    if [ ! -e "$f" -a "${f#/}" = "$f" ] ; then
-		# $f is relative, try in $CTDB_BASE
-		f="${CTDB_BASE}/${f}"
-	    fi
-	elif [ -n "$CTDB_NODES" ] ; then
-	    f="$CTDB_NODES"
+	if [ -n "$ctdb_nodes_file" ] ; then
+		f="$ctdb_nodes_file"
+		if [ ! -e "$f" -a "${f#/}" = "$f" ] ; then
+			# $f is relative, try in $CTDB_BASE
+			f="${CTDB_BASE}/${f}"
+		fi
 	fi
 
 	if [ ! -r "$f" ] ; then
-	    echo "${prog}: unable to open nodes file  \"${f}\"" >&2
-	    exit 1
+		echo "${prog}: unable to open nodes file  \"${f}\"" >&2
+		exit 1
 	fi
 
 	all_nodes=$(sed -e 's@#.*@@g' -e 's@ *@@g' -e 's@^$@#DEAD@' "$f")
-    fi
 
-    local n nodes
-    nodes=$(parse_nodespec "$1") || exit $?
-    for n in $nodes ; do
-	case "$n" in
-	    all)
-		echo "${all_nodes//#DEAD/}"
-		;;
-	    any)
-		get_any_available_node "$all_nodes" || exit 1
-		;;
-	    ok|healthy) 
-		get_nodes_with_status "$all_nodes" "healthy" || exit 1
-		;;
-	    con|connected) 
-		get_nodes_with_status "$all_nodes" "connected" || exit 1
-		;;
-	    [0-9]|[0-9][0-9]|[0-9][0-9][0-9])
-		# Intentional multi-word expansion
-		# shellcheck disable=SC2086
-		echo_nth "$n" $all_nodes
-		;;
-	    *)
-		$names_ok || invalid_nodespec
-		echo "$n"
-	esac
-    done
+	local n nodes
+	nodes=$(parse_nodespec "$1") || exit $?
+	for n in $nodes ; do
+		case "$n" in
+		all)
+			echo "${all_nodes//#DEAD/}"
+			;;
+		any)
+			get_any_available_node "$all_nodes" || exit 1
+			;;
+		ok|healthy)
+			get_nodes_with_status "$all_nodes" "healthy" || exit 1
+			;;
+		con|connected)
+			get_nodes_with_status "$all_nodes" "connected" || exit 1
+			;;
+		[0-9]|[0-9][0-9]|[0-9][0-9][0-9])
+			# Intentional multi-word expansion
+			# shellcheck disable=SC2086
+			echo_nth "$n" $all_nodes
+			;;
+		*)
+			$names_ok || invalid_nodespec
+			echo "$n"
+		esac
+	done
 }
 
 push()
@@ -283,11 +266,6 @@ push()
 	    *)  rsync "${PWD}/${f}" "[${host}]:${PWD}/${f}" ;;
 	esac
     done
-}
-
-fakessh ()
-{
-    CTDB_SOCKET="$1" sh -c "$2" 3>/dev/null
 }
 
 stdout_filter ()
@@ -316,26 +294,21 @@ parse_options "$@"
 
 ssh_opts=
 if $push ; then
-    SSH=push
-    EXTRA_SSH_OPTS=""
+	ONNODE_SSH=push
+	ONNODE_SSH_OPTS=""
 else
-    $current && command="cd $PWD && $command"
+	$current && command="cd $PWD && $command"
 
-    if [ -n "$CTDB_NODES_SOCKETS" ] ; then
-	SSH=fakessh
-	EXTRA_SSH_OPTS=""
-    else 
 	# Could "2>/dev/null || true" but want to see errors from typos in file.
 	[ -r "${CTDB_BASE}/onnode.conf" ] && . "${CTDB_BASE}/onnode.conf"
-	[ -n "$SSH" ] || SSH=ssh
-	if [ "$SSH" = "ssh" ] ; then
-	    if $parallel || ! $stdin ; then
-		ssh_opts="-n"
-	    fi
+	[ -n "$ONNODE_SSH" ] || ONNODE_SSH=ssh
+	if [ "$ONNODE_SSH" = "ssh" ] ; then
+		if $parallel || ! $stdin ; then
+			ssh_opts="-n"
+		fi
 	else
-	    : # rsh? All bets are off!
+		: # rsh? All bets are off!
 	fi
-    fi
 fi
 
 ######################################################################
@@ -360,42 +333,38 @@ trap 'kill -TERM $pids 2>/dev/null' INT TERM
 # the part of the window where it matter is very small.
 retcode=0
 for n in $nodes ; do
-    set -o pipefail 2>/dev/null
+	set -o pipefail 2>/dev/null
 
-    # The following code applies stdout_filter and stderr_filter to
-    # the relevant streams.  Both filters are at the end of pipes so
-    # they read from stdin and (by default) write to stdout.  To allow
-    # the filters to operate independently, the output of
-    # stdout_filter is sent to a temporary file descriptor (3), which
-    # is redirected back to stdout at the outermost level.
-    if $parallel ; then
-	{
-	    exec 3>&1
-	    {
-		$SSH $ssh_opts $EXTRA_SSH_OPTS "$n" "$command" |
-		    stdout_filter >&3
-	    } 2>&1 | stderr_filter
-	} &
-	pids="${pids} $!"
-    else
-	if $verbose ; then
-	    echo >&2 ; echo ">> NODE: $n <<" >&2
+	# The following code applies stdout_filter and stderr_filter to
+	# the relevant streams.  Both filters are at the end of pipes so
+	# they read from stdin and (by default) write to stdout.  To allow
+	# the filters to operate independently, the output of
+	# stdout_filter is sent to a temporary file descriptor (3), which
+	# is redirected back to stdout at the outermost level.
+	ssh_cmd="$ONNODE_SSH $ssh_opts $ONNODE_SSH_OPTS"
+	if $parallel ; then
+		{
+			exec 3>&1
+			{
+				$ssh_cmd "$n" "$command" 3>&- |
+					stdout_filter >&3
+			} 2>&1 | stderr_filter
+		} &
+		pids="${pids} $!"
+	else
+		if $verbose ; then
+			echo >&2 ; echo ">> NODE: $n <<" >&2
+		fi
+		{
+			$ssh_cmd "$n" "$command" | stdout_filter
+		} || retcode=$?
 	fi
-
-	{
-	    exec 3>&1
-	    {
-		$SSH $ssh_opts $EXTRA_SSH_OPTS "$n" "$command" |
-		    stdout_filter >&3
-	    } 2>&1 | stderr_filter
-	} || retcode=$?
-    fi
 done
 
 if $parallel ; then
-    for p in $pids; do
-	wait "$p" || retcode=$?
-    done
+	for p in $pids; do
+		wait "$p" || retcode=$?
+	done
 fi
 
 exit $retcode
