2:4.5.0+dfsg-1 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/ctdb/config/nfs-linux-kernel-callout b/ctdb/config/nfs-linux-kernel-callout
--- a/ctdb/config/nfs-linux-kernel-callout
+++ b/ctdb/config/nfs-linux-kernel-callout
@@ -36,7 +36,7 @@ fi
 
 usage ()
 {
-    _c=$(basename $0)
+    _c=$(basename "$0")
     cat <<EOF
 usage: $_c { shutdown | startup }
        $_c { stop | start } { nfs | nlockmgr }
@@ -165,9 +165,13 @@ nfs_check_thread_count ()
     # nfsd should be running the configured number of threads.  If
     # there are a different number of threads then tell nfsd the
     # correct number.
-    read _running_threads <"$_threads_file"
+    read _running_threads <"$_threads_file" || {
+	    echo "WARNING: Reading \"${_threads_file}\" unexpectedly failed"
+	    exit 0
+    }
+
     # Intentionally not arithmetic comparison - avoids extra errors
-    # when above fails...
+    # when above read fails in an unexpected way...
     if [ "$_running_threads" != "$_configured_threads" ] ; then
 	echo "Attempting to correct number of nfsd threads from ${_running_threads} to ${_configured_threads}"
 	echo "$_configured_threads" >"$_threads_file"
@@ -180,6 +184,8 @@ nfs_check_thread_count ()
 nfs_monitor_list_shares ()
 {
     _cache_file="${CTDB_NFS_CALLOUT_STATE_DIR}/list_shares_cache"
+    # -nt operator is well supported in Linux: dash, bash, ksh, ...
+    # shellcheck disable=SC2039
     if  [ ! -r "$nfs_exports_file" ] || [ ! -r "$_cache_file" ] || \
 	    [ "$nfs_exports_file" -nt "$_cache_file" ] ; then
 	mkdir -p "$CTDB_NFS_CALLOUT_STATE_DIR"
@@ -238,7 +244,7 @@ case "$1" in
     register)
 	nfs_register
 	;;
-    monitor-pre|releaseip|takeip)
+    monitor-pre|releaseip|takeip|releaseip-pre|takeip-pre)
 	# Not required/implemented
 	:
 	;;
diff --git a/ctdb/doc/examples/nfs-ganesha-callout b/ctdb/doc/examples/nfs-ganesha-callout
--- a/ctdb/doc/examples/nfs-ganesha-callout
+++ b/ctdb/doc/examples/nfs-ganesha-callout
@@ -14,10 +14,19 @@
 # * Set CTDB_NFS_CALLOUT in your CTDB configuration to point to this
 #   script
 #
-# * Rename nfs-checks.d/{20.nfs.check,30.nlockmgr.check,50.mountd.check}
-#   so that they no longer have the ".check" suffix
+# * Rename the following files in nfs-checks.d so that they no longer
+#   have the ".check" suffix:
+#     * 10.status.check
+#     * 20.nfs.check
+#     * 30.nlockmgr.check
+#     * 40.mountd.check
+#     * 50.rquotad.check
 #
 # * Install 20.nfs-ganesha.check to nfs-checks.d/20.nfs.check
+#
+# * It is recommended, but not required, to install the grace_period
+#   script (usually shipped in a utils package for NFS-Ganesha) to
+#   /usr/bin/grace_period
 
 # I (Martin Schwenke) hereby relicense all of my contributions to this
 # callout (and, previously, to 60.ganesha) to a license compatible
@@ -30,14 +39,34 @@
 # Exit on 1st error
 set -e
 
-if [ -z "$CTDB_CLUSTER_FILESYSTEM_TYPE" ] ; then
-    CTDB_CLUSTER_FILESYSTEM_TYPE="gpfs"
-fi
+# Filesystem type and mount point for the (typically clustered)
+# volume that will contain the NFS-Ganesha state.
+state_fs="${CTDB_NFS_STATE_FS_TYPE:-gpfs}"
+state_dir="${CTDB_NFS_STATE_MNT}" # No sane default.
 
-# Override for unit testing
-if [ -z "$PROCFS_PATH" ] ; then
-    PROCFS_PATH="/proc"
-fi
+# To change the following, edit the default values below.  Do not set
+# these - they aren't configuration variables, just hooks for testing.
+nfs_exports_file="${CTDB_NFS_EXPORTS_FILE:-/etc/ganesha/ganesha.conf}"
+nfs_service="${CTDB_NFS_SERVICE:-nfs-ganesha}"
+ganesha_rec_subdir=${CTDB_GANESHA_REC_SUBDIR:-.ganesha}
+procfs=${PROCFS_PATH:-/proc}
+
+case $state_fs in
+    gpfs)
+        GANRECDIR="/var/lib/nfs/ganesha"
+        ;;
+    glusterfs)
+        if [ -z "${state_dir}" ]; then
+            echo "CTDB_NFS_STATE_MNT not defined for GlusterFS"
+            exit 1
+        fi
+        host=`hostname`
+        NODESTATEDIR="$state_dir/nfs-ganesha/$host"
+        GANSTATEDIR="$state_dir/nfs-ganesha/.noderefs"
+        NODESTATELN="$GANSTATEDIR/$host"
+        ;;
+esac
+
 
 ##################################################
 
@@ -56,8 +85,6 @@ EOF
 
 ##################################################
 # Basic service stop and start
-
-nfs_service="nfs-ganesha-$CTDB_CLUSTER_FILESYSTEM_TYPE"
 
 basic_stop ()
 {
@@ -117,52 +144,82 @@ service_start ()
 ##################################################
 # Nitty gritty - monitoring and IP handling
 
-GANRECDIR="/var/lib/nfs/ganesha"
-GANRECDIR2="/var/lib/nfs/ganesha/recevents"
-GANRECDIR3="/var/lib/nfs/ganesha_local"
+# Check that a symlink exists, create it otherwise.
+# Usage: check_ln <TARGET> <LINK>
+check_ln ()
+{
+    if [ ! -L "${2}" ] ; then
+        rm -vrf "${2}"
+    else
+        _t=$(readlink "${2}")
+        if [ "$_t" != "${1}" ] ; then
+            rm -v "${2}"
+        fi
+    fi
+    # This is not an "else".  It also re-creates the link if it was
+    # removed above!
+    if [ ! -e "${2}" ]; then
+        ln -sfv "${1}" "${2}"
+    fi
+}
 
+# Return 'active' if the shared filesystem is accessible.
 get_cluster_fs_state ()
 {
-    case $CTDB_CLUSTER_FILESYSTEM_TYPE in
+    case $state_fs in
         gpfs)
             /usr/lpp/mmfs/bin/mmgetstate | awk 'NR == 4 { print $3 }'
             ;;
+        glusterfs)
+            # Since we're past create_ganesha_recdirs(), we're active.
+            echo "active"
+            ;;
         *)
-            die "File system $CTDB_CLUSTER_FILESYSTEM_TYPE not supported"
+            echo "File system $state_fs not supported"
+            exit 1
             ;;
    esac
 }
 
 create_ganesha_recdirs ()
 {
-    [ -n "$CTDB_GANESHA_REC_SUBDIR" ] || CTDB_GANESHA_REC_SUBDIR=".ganesha"
-
-    _mounts=$(mount -t $CTDB_CLUSTER_FILESYSTEM_TYPE)
+    if ! _mounts=$(mount | grep $state_fs); then
+      echo "Failed to find mounts of type $state_fs"
+      exit 1
+    fi
     if [ -z "$_mounts" ]; then
-      echo "startup $CTDB_CLUSTER_FILESYSTEM_TYPE not ready"
+      echo "startup $state_fs not ready"
       exit 0
     fi
-    _mntpt=$(echo "$_mounts" | sort | awk 'NR == 1 {print $3}')
-    _link_dst="${_mntpt}/${CTDB_GANESHA_REC_SUBDIR}"
-    mkdir -vp "$_link_dst"
-    if [ -e "$GANRECDIR" ]; then
-        if [ ! -L "$GANRECDIR" ] ; then
-            rm -vrf "$GANRECDIR"
-	else
-	    _t=$(readlink "$GANRECDIR")
-	    if [ "$_t" != "$_link_dst" ] ; then
-		rm -v "$GANRECDIR"
-	    fi
-        fi
-    fi
-    # This is not an "else".  It also re-creates the link if it was
-    # removed above!
-    if [ ! -e "$GANRECDIR" ]; then
-        ln -sv "$_link_dst" "$GANRECDIR"
-    fi
 
-    mkdir -p "$GANRECDIR2"
-    mkdir -p "$GANRECDIR3"
+    case $state_fs in
+        gpfs)
+            _mntpt=$(echo "$_mounts" | sort | awk 'NR == 1 {print $3}')
+            _link_dst="${_mntpt}/${ganesha_rec_subdir}"
+            mkdir -vp "$_link_dst"
+            check_ln "$_link_dst" "$GANRECDIR"
+            ;;
+        glusterfs)
+            [ -d /var/lib/nfs.backup ] || mv /var/lib/nfs /var/lib/nfs.backup
+            check_ln ${NODESTATEDIR} /var/lib/nfs
+
+            mkdir -p ${NODESTATEDIR}/ganesha/v4recov
+            mkdir -p ${NODESTATEDIR}/ganesha/v4old
+            mkdir -p ${NODESTATEDIR}/statd/sm
+            mkdir -p ${NODESTATEDIR}/statd/sm.bak
+            touch ${NODESTATEDIR}/state
+            touch ${NODESTATEDIR}/statd/state
+
+            mkdir -p ${GANSTATEDIR}
+            check_ln ${NODESTATEDIR} ${NODESTATELN}
+            for node in `ls ${GANSTATEDIR}`; do
+                if [ "${node}" != "${host}" ]; then
+                    check_ln ${GANSTATEDIR}/${node}/ganesha ${NODESTATEDIR}/ganesha/${node}
+                    check_ln ${GANSTATEDIR}/${node}/statd ${NODESTATEDIR}/statd/${node}
+                fi
+            done
+            ;;
+   esac
 }
 
 service_check ()
@@ -172,35 +229,15 @@ service_check ()
     # Always succeed if cluster filesystem is not active
     _cluster_fs_state=$(get_cluster_fs_state)
     if [ $_cluster_fs_state != "active" ] ; then
-	exit 0
+	return 0
     fi
 
     # Check that NFS Ganesha is running, according to PID file
     _pidfile="/var/run/ganesha.pid"
-    _ganesha="/usr/bin/$CTDB_CLUSTER_FILESYSTEM_TYPE.ganesha.nfsd"
+    _ganesha="/usr/bin/ganesha.nfsd"
     if ! { read _pid < "$_pidfile" && \
-	   grep "$_ganesha" "${PROCFS_PATH}/${_pid}/cmdline" ; } >/dev/null 2>&1 ; then
+	   grep "$_ganesha" "${procfs}/${_pid}/cmdline" ; } >/dev/null 2>&1 ; then
 	echo "ERROR: NFS Ganesha not running according to PID file"
-	return 1
-    fi
-
-    # Check red conditions against limit
-    _reds_max=2
-    _reds=$(ls $GANRECDIR3 | grep -c "red")
-
-    if [ $_reds -ge $_reds_max ] ; then
-	echo "Too many red conditions (${_reds}/${_reds_max})"
-	return 1
-    fi
-
-    # Check for stall
-    _stall_max=120
-    _now=$(date +"%s")
-    _last=$(ls -t $GANRECDIR3 | sed -n -e '1s@_.*@@p')
-    [ -n $_last ] || _last=$_now  # Handle startup
-    _stall=$(($_now - $_last))
-    if [ $_stall -ge $_stall_max ] ; then
-	echo "ERROR: Stalled for ${_stall} second(s)"
 	return 1
     fi
 
@@ -209,41 +246,31 @@ service_check ()
 
 #-------------------------------------------------
 
-get_nodenum ()
-{
-    _nodenum_file="${GANRECDIR}/gpfs_nodenum"
-
-    if [ ! -f "$_nodenum_file" ]; then
-	/usr/lpp/mmfs/bin/mmlsconfig myNodeConfigNumber |
-	    awk '{print $2}' >"$_nodenum_file"
-    fi
-
-    cat "$_nodenum_file"
-}
-
 nfs_releaseip ()
 {
-    case  $CLUSTER_FILESYSTEM_TYPE in
-	gpfs)
-	    _nnum=$(get_nodenum)
-	    _tdate=$(date +"%s")
-	    _touchtgt="releaseip_${_tdate}_${_nnum}_${2}_${3}_${1}"
-	    touch "${GANRECDIR2}/${_touchtgt}"
-	    touch "$GANRECDIR2/my${_touchtgt}"
-	    ;;
-    esac
+    if [ -x "/usr/bin/grace_period" ]; then
+        /usr/bin/grace_period "2:${2}"
+    else
+        dbus-send --print-reply --system --dest=org.ganesha.nfsd \
+        /org/ganesha/nfsd/admin org.ganesha.nfsd.admin.grace \
+        string:"2:${2}"
+    fi
 }
 
 nfs_takeip ()
 {
-    case  $CLUSTER_FILESYSTEM_TYPE in
-	gpfs)
-	    _nnum=$(get_nodenum)
-	    _tdate=$(date +"%s")
-	    _touchtgt="takeip_${_tdate}_${_nnum}_${2}_${3}_${1}"
-	    touch "${GANRECDIR2}/${_touchtgt}"
-	    ;;
+    case  $state_fs in
+        glusterfs)
+            check_ln ${NODESTATEDIR} ${GANSTATEDIR}/${2}
+            ;;
     esac
+    if [ -x "/usr/bin/grace_period" ]; then
+        /usr/bin/grace_period "5:${2}"
+    else
+        dbus-send --print-reply --system --dest=org.ganesha.nfsd \
+        /org/ganesha/nfsd/admin org.ganesha.nfsd.admin.grace \
+        string:"5:${2}"
+    fi
 }
 
 ##################################################
@@ -256,11 +283,12 @@ nfs_shutdown ()
 
 nfs_startup ()
 {
+    basic_stop "nfs" || true
+
     create_ganesha_recdirs
 
-    basic_stop "nfs" || true
     basic_start "nfs"
-    _f="${PROCFS_PATH}/sys/net/ipv4/tcp_tw_recycle"
+    _f="${procfs}/sys/net/ipv4/tcp_tw_recycle"
     if [ "$_f" ] ; then
 	echo 1 >"$_f"
     fi
@@ -271,9 +299,25 @@ nfs_startup ()
 
 nfs_monitor_list_shares ()
 {
-    grep Path /etc/ganesha/$CTDB_CLUSTER_FILESYSTEM_TYPE.ganesha.exports.conf |
+    grep Path $nfs_exports_file |
 	cut -f2 -d\" |
 	sort -u
+}
+
+##################################################
+
+nfs_register ()
+{
+    cat <<EOF
+shutdown
+startup
+stop
+start
+check
+releaseip
+takeip
+monitor-list-shares
+EOF
 }
 
 ##################################################
@@ -290,7 +334,8 @@ case "$action" in
     releaseip)           nfs_releaseip "$@"      ;;
     takeip)              nfs_takeip "$@"         ;;
     monitor-list-shares) nfs_monitor_list_shares ;;
-    register|monitor-pre|monitor-post)
+    register)            nfs_register            ;;
+    monitor-pre|monitor-post|releaseip-pre|takeip-pre)
 	# Not required/implemented
 	:
 	;;
diff --git a/ctdb/tools/ctdb_diagnostics b/ctdb/tools/ctdb_diagnostics
--- a/ctdb/tools/ctdb_diagnostics
+++ b/ctdb/tools/ctdb_diagnostics
@@ -57,7 +57,7 @@ esac
 # them to $bad_nodes.
 _nodes=""
 for _i in $nodes ; do
-    if onnode $_i true >/dev/null 2>&1 ; then
+    if onnode "$_i" true >/dev/null 2>&1 ; then
 	_nodes="${_nodes}${_nodes:+ }${_i}"
     else
 	bad_nodes="${bad_nodes}${bad_nodes:+,}${_i}"
@@ -65,7 +65,7 @@ for _i in $nodes ; do
 done
 nodes="$_nodes"
 
-nodes_comma=$(echo $nodes | sed -e 's@[[:space:]]@,@g')
+nodes_comma=$(echo "$nodes" | sed -e 's@[[:space:]]@,@g')
 
 PATH="$PATH:/sbin:/usr/sbin:/usr/lpp/mmfs/bin"
 
@@ -96,22 +96,23 @@ date
 error() {
     msg="$1"
     echo "ERROR: $msg"
-    NUM_ERRORS=`expr $NUM_ERRORS + 1`
-    echo " ERROR[$NUM_ERRORS]: $msg" >> $ERRORS
+    NUM_ERRORS=$((NUM_ERRORS + 1))
+    echo " ERROR[$NUM_ERRORS]: $msg" >> "$ERRORS"
 }
 
 show_file() {
     fname="$1"
+    _fdetails=$(ls -l "$fname" 2>&1)
     echo "  ================================"
     echo "  File: $fname"
-    echo "  `ls -l $fname 2>&1`"
-    cat "$fname" 2>&1 | sed 's/^/  /'
+    echo "  $_fdetails"
+    sed 's/^/  /' "$fname" 2>&1
     echo "  ================================"
 }
 
 show_all() {
     echo "running $1 on nodes $nodes_comma"
-    onnode $nodes_comma "hostname; date; $1 2>&1 | sed 's/^/  /'" 2>&1
+    onnode "$nodes_comma" "hostname; date; $1 2>&1 | sed 's/^/  /'" 2>&1
 }
 
 show_and_compare_files () {
@@ -119,39 +120,45 @@ show_and_compare_files () {
     fmt="$1" ; shift
 
     for f ; do
+	_bf=$(basename "$f")
 	first=true
 
 	for n in $nodes ; do
 
 	    if $first ; then
-		onnode $n [ -r "$f" ] || {
-		    msg=$(printf "$fmt" "$f" $n)
+		onnode "$n" [ -r "$f" ] || {
+		    # This function takes a format string
+		    # shellcheck disable=SC2059
+		    msg=$(printf "$fmt" "$f" "$n")
 		    error "$msg"
 		    continue 2;
 		}
 
-		fstf=$tmpdir/`basename $f`.node$n
-		onnode $n cat $f > $fstf 2>&1
+		fstf="${tmpdir}/${_bf}.node${n}"
+		onnode "$n" cat "$f" >"$fstf" 2>&1
 
+		_fdetails=$(onnode "$n" ls -l "$f" 2>&1)
 		echo "  ================================"
 		echo "  File (on node $n): $f"
-		echo "  `onnode $n ls -l $f 2>&1`"
-		cat "$fstf" | sed 's/^/  /'
+		echo "  $_fdetails"
+		sed 's/^/  /' "$fstf"
 		echo "  ================================"
 		first=false
 	    else
 		echo "Testing for same config file $f on node $n"
-		tmpf=$tmpdir/`basename $f`.node$n
-		onnode $n cat $f > $tmpf 2>&1
-		diff $diff_opts $fstf $tmpf >/dev/null 2>&1 || {
+		tmpf="${tmpdir}/${_bf}.node${n}"
+		onnode "$n" cat "$f" >"$tmpf" 2>&1
+		# Intentional multi-word splitting on diff_opts
+		# shellcheck disable=SC2086
+		diff $diff_opts "$fstf" "$tmpf" >/dev/null 2>&1 || {
 		    error "File $f is different on node $n"
-		    diff -u $diff_opts $fstf $tmpf
+		    diff -u $diff_opts "$fstf" "$tmpf"
 		}
-		rm -f $tmpf
+		rm -f "$tmpf"
 	    fi
 	done
 
-	rm -f $fstf
+	rm -f "$fstf"
     done
 }
 
@@ -188,10 +195,14 @@ cat <<EOF
 Comping critical config files on nodes $nodes_comma
 EOF
 
+# Intentional multi-word splitting on CONFIG_FILES_MUST
+# shellcheck disable=SC2086
 show_and_compare_files \
     "%s is missing on node %d" \
     $CONFIG_FILES_MUST
 
+# Intentional multi-word splitting on CONFIG_FILES_MAY
+# shellcheck disable=SC2086
 show_and_compare_files \
     "Optional file %s is not present on node %d" \
     $CONFIG_FILES_MAY
@@ -200,11 +211,11 @@ cat <<EOF
 --------------------------------------------------------------------
 Checking for clock drift
 EOF
-t=`date +%s`
+t=$(date +%s)
 for i in $nodes; do
-    t2=`onnode $i date +%s`
-    d=`expr $t2 - $t`
-    if [ $d -gt 30 -o $d -lt -30 ]; then
+    t2=$(onnode "$i" date +%s)
+    d=$((t2 - t))
+    if [ "$d" -gt 30 -o "$d" -lt -30 ]; then
 	error "time on node $i differs by $d seconds"
     fi
 done
@@ -315,7 +326,7 @@ else
 fi
 show_all "date"
 show_all "smbclient -U% -L 127.0.0.1"
-WORKGROUP=`testparm -s --parameter-name=WORKGROUP 2> /dev/null`
+WORKGROUP=$(testparm -s --parameter-name=WORKGROUP 2> /dev/null)
 show_all id "$WORKGROUP/Administrator"
 show_all "wbinfo -p"
 show_all "wbinfo --online-status"
@@ -324,9 +335,9 @@ show_all "smbd -b"
 date
 echo "Diagnostics finished with $NUM_ERRORS errors"
 
-[ -r $ERRORS ] && {
-    cat $ERRORS
-    rm -f $ERRORS
+[ -r "$ERRORS" ] && {
+    cat "$ERRORS"
+    rm -f "$ERRORS"
 }
 
 rm -rf "$tmpdir"
