2:4.4.4+dfsg-2 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/debian/samba.postinst b/debian/samba.postinst
--- a/debian/samba.postinst
+++ b/debian/samba.postinst
@@ -76,6 +76,26 @@ then
 	install -d -m 1770 -g sambashare /var/lib/samba/usershares
 fi
 
+# mimic source4/smbd/server.c and mask service before it fails
+SERVER_ROLE=`samba-tool testparm --parameter-name="server role"  2>/dev/null | tail -1`
+SERVER_SERVICES=`samba-tool testparm --parameter-name="server services"  2>/dev/null | tail -1`
+DCERPC_ENDPOINT_SERVERS=`samba-tool testparm --parameter-name="dcerpc endpoint servers"  2>/dev/null | tail -1`
+if [ "$SERVER_ROLE" != "active directory domain controller" ] \
+	&& ( echo "$SERVER_SERVICES" | grep -qv '\(^\|, \)smb\(,\|$\)' ) \
+	&& ( echo "$DCERPC_ENDPOINT_SERVERS" | grep -qv '\(^\|, \)remote\(,\|$\)' ) \
+	&& ( echo "$DCERPC_ENDPOINT_SERVERS" | grep -qv '\(^\|, \)mapiproxy\(,\|$\)' ) \
+; then
+    if [ ! -e /etc/systemd/system/samba-ad-dc.service ]; then
+        mkdir -p /etc/systemd/system
+        ln -s /dev/null /etc/systemd/system/samba-ad-dc.service
+        # In case this system is running systemd, we make systemd reload the unit files
+        # to pick up changes.
+        if [ -d /run/systemd/system ] ; then
+            systemctl --system daemon-reload >/dev/null || true
+        fi
+	fi
+fi
+
 #DEBHELPER#
 
 exit 0
